### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by oxyroid** [GameTheory-/jodin3#3]
When I click "Start", message dialog always "<ID:0/008> Added!!Device Connected", but console shows:
```
Exception in thread "Thread-31" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at CASUAL.communicationstools.heimdall.odin.OdinFile.extractOdinContents(OdinFile.java:145)
	at CASUAL.communicationstools.heimdall.odin.Odin.getHeimdallFileParametersFromOdinFile(Odin.java:50)
	at com.casual_dev.jodin.JOdinController.getHeimdallCommandFromOdinPackageList(JOdinController.java:621)
	at com.casual_dev.jodin.JOdinController.access$3300(JOdinController.java:54)
	at com.casual_dev.jodin.JOdinController$13.run(JOdinController.java:572)
	at java.base/java.lang.Thread.runWith(Thread.java:1636)
	at java.base/java.lang.Thread.run(Thread.java:1623)
[VERBOSE]Heimdall Device detected!
[VERBOSE]Heimdall Device detected!
[VERBOSE]Heimdall Device detected!
...
```

**Comment by oxyroid** [comment]
Always Running.

**Comment by rmortes** [comment]
Same, I'm unable to flash my phone. MacBook Air M2 14.4, openjdk version "20.0.2" 2023-07-18

**Comment by oxyroid** [comment]
Finally, I install windows virtual machine.

**Comment by ghost** [comment]
> Same, I'm unable to flash my phone. MacBook Air M2 14.4, openjdk version "20.0.2" 2023-07-18

Pro tip: Don't waste money on a CrapBook Air. Just get a normal laptop

**Comment by rmortes** [comment]
> > Same, I'm unable to flash my phone. MacBook Air M2 14.4, openjdk version "20.0.2" 2023-07-18
> 
> Pro tip: Don't waste money on a CrapBook Air. Just get a normal laptop

Thanks for the tip, but that was uncalled for. If I may give you a tip of my own, please don't assume things about people you don't know on the internet. My computed could've been a gift, I could need a mac based system to develop for iOS, I could have a disability and be used to the MacOS accessibility features, or I could simply like the hardware or software better than the alternatives. You don't know why I use a MacBook Air, and that comment was really out of place here.
